### ISSUE TITLE
Fix for one output error

### ISSUE THREAD

**Issue by ZEROF** [opsdisk/metagoofil#11]
Hi,

Was getting this error:

Traceback (most recent call last):
 File "./metagoofil.py", line 226, in <module>
   mg.go()
 File "./metagoofil.py", line 146, in go
   self.html_links.close()
AttributeError: Metagoofil instance has no attribute 'html_links'

**Fix**

From:

```
            if self.save_links:
                for f in self.files:
                    self.html_links.write(f + "\n")

        self.html_links.close()
```

To:
```

            if self.save_links:
                for f in self.files:
                    self.html_links.write(f + "\n")
        if self.save_links:
            self.html_links.close()
```

**Comment by opsdisk** [comment]
Thanks for taking the time to submit an issue @ZEROF .  Do you want to submit a pull request to get contributor credit?  If not, I can just add it.

**Comment by ZEROF** [comment]
U welcome. Sure, I will send pull request ;)

**Comment by opsdisk** [comment]
See https://github.com/opsdisk/metagoofil/pull/12
