### ISSUE TITLE
`pip install -r requirements.txt` not working, results in `No matching distribution found for requests==2.28.1`

### ISSUE THREAD

**Issue by zdavatz** [opsdisk/metagoofil#31]
1. I do ` pip install -r requirements.txt`
2. This results in
```
 pip install -r requirements.txt
Collecting google==3.0.0
  Using cached google-3.0.0-py2.py3-none-any.whl (45 kB)
ERROR: Could not find a version that satisfies the requirement requests==2.28.1 (from versions: 0.2.0, 0.2.1, 0.2.2, 0.2.3, 0.2.4, 0.3.0, 0.3.1, 0.3.2, 0.3.3, 0.3.4, 0.4.0, 0.4.1, 0.5.0, 0.5.1, 0.6.0, 0.6.1, 0.6.2, 0.6.3, 0.6.4, 0.6.5, 0.6.6, 0.7.0, 0.7.1, 0.7.2, 0.7.3, 0.7.4, 0.7.5, 0.7.6, 0.8.0, 0.8.1, 0.8.2, 0.8.3, 0.8.4, 0.8.5, 0.8.6, 0.8.7, 0.8.8, 0.8.9, 0.9.0, 0.9.1, 0.9.2, 0.9.3, 0.10.0, 0.10.1, 0.10.2, 0.10.3, 0.10.4, 0.10.6, 0.10.7, 0.10.8, 0.11.1, 0.11.2, 0.12.0, 0.12.1, 0.13.0, 0.13.1, 0.13.2, 0.13.3, 0.13.4, 0.13.5, 0.13.6, 0.13.7, 0.13.8, 0.13.9, 0.14.0, 0.14.1, 0.14.2, 1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.1.0, 1.2.0, 1.2.1, 1.2.2, 1.2.3, 2.0.0, 2.0.1, 2.1.0, 2.2.0, 2.2.1, 2.3.0, 2.4.0, 2.4.1, 2.4.2, 2.4.3, 2.5.0, 2.5.1, 2.5.2, 2.5.3, 2.6.0, 2.6.1, 2.6.2, 2.7.0, 2.8.0, 2.8.1, 2.9.0, 2.9.1, 2.9.2, 2.10.0, 2.11.0, 2.11.1, 2.12.0, 2.12.1, 2.12.2, 2.12.3, 2.12.4, 2.12.5, 2.13.0, 2.14.0, 2.14.1, 2.14.2, 2.15.1, 2.16.0, 2.16.1, 2.16.2, 2.16.3, 2.16.4, 2.16.5, 2.17.0, 2.17.1, 2.17.2, 2.17.3, 2.18.0, 2.18.1, 2.18.2, 2.18.3, 2.18.4, 2.19.0, 2.19.1, 2.20.0, 2.20.1, 2.21.0, 2.22.0, 2.23.0, 2.24.0, 2.25.0, 2.25.1, 2.26.0, 2.27.0, 2.27.1)
ERROR: No matching distribution found for requests==2.28.1
```

**Comment by opsdisk** [comment]
Hi @zdavatz 

It doesn't look like the 2.28.1 version was removed or revoked (https://github.com/psf/requests/releases/tag/v2.28.1).  I just installed it in a Linux 3.10.6 virtual environment without any issues.

1) What version of Python are you using?
2) Are you using a virtual environment?
3) Maybe it's a pip cache issue (see https://linuxhint.com/pip-clear-cache/)?  It's not showing 2.28.2 (which is the latest) in your output as a valid candidate either.

**Comment by zdavatz** [comment]
> Hi @zdavatz
> 
> It doesn't look like the 2.28.1 version was removed or revoked (https://github.com/psf/requests/releases/tag/v2.28.1). I just installed it in a Linux 3.10.6 virtual environment without any issues.
> 
> 1. What version of Python are you using?
Python 3.6.8
> 2. Are you using a virtual environment?
Yes, as mentioned in the how-to.

> 3. Maybe it's a pip cache issue (see https://linuxhint.com/pip-clear-cache/)?  It's not showing 2.28.2 (which is the latest) in your output as a valid candidate either.

Which command shall I issue?

**Comment by zdavatz** [comment]
Doing these steps:
```
virtualenv -p python3 .venv
source .venv/bin/activate
pip install -r requirements.txt
```

**Comment by zdavatz** [comment]
Same problem with Python 3.9:
<img width="1138" alt="Bildschirm­foto 2023-03-13 um 18 27 26" src="https://user-images.githubusercontent.com/4953/224780272-5a775411-c185-49d5-addc-32c6f2606431.png">

**Comment by opsdisk** [comment]
Looks like they removed support for Python 3.6 in version 2.28.0 https://github.com/psf/requests/blob/main/HISTORY.md#2281-2022-06-29

That doesn't explain your 3.9 issue though.  Short term, you could downgrade the `requests` version in the `requirements.txt` file until you find one that works.

![image](https://user-images.githubusercontent.com/8660252/224781442-bc7c6470-5788-49f1-8179-640c4d0d630c.png)

**Comment by zdavatz** [comment]
Downgrade to which version?

**Comment by opsdisk** [comment]
Based off your screenshot, you could try 2.27.1

**Comment by zdavatz** [comment]
This worked! 🙏 Where is the installed binary now?

**Comment by opsdisk** [comment]
Great!  It doesn't create a binary.  You should be able to run this in your Python virtual environment:

`python metagoofil.py -h`

**Comment by zdavatz** [comment]
this worked, thank you!
