### ISSUE TITLE
No module named google

### ISSUE THREAD

**Issue by honoki** [opsdisk/metagoofil#5]
Having installed `pip install google`, this version of metagoofil errors with "ImportError: No module named google"

My fix was to replace "google" by "googlesearch" 3 times in lines 7 and 105 of `metagoofil.py`.

**Comment by opsdisk** [comment]
Thanks for the heads up @honoki ...updated the library and upgrading the code.  Should have it out in few days.

**Comment by opsdisk** [comment]
Here's the branch if you want to take it for a test drive.  You'll have to rerun `pip install -r requirements.txt`

https://github.com/opsdisk/metagoofil/tree/googlesearch-update

**Comment by opsdisk** [comment]
master branch now has updated code.
